### ISSUE TITLE
Can't upload image

### ISSUE THREAD

**Issue by gregv** [opportunity-hack/ai-coloring-book#5]
Can't upload image at http://localhost:3001/drawings

![image](https://github.com/2023-opportunity-hack/Caffeine-Compilers--FromSketchestoSmiles-AColoringBookthatGivesBack/assets/6913307/259ceb7b-3519-41e4-bc55-d4e8c450decf)

Error
```
[16/Feb/2024 02:46:11] "POST /api/upload_drawings/ HTTP/1.1" 500 145250
Internal Server Error: /api/upload_drawings/
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/sketch/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/sketch/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/sketch/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/sketch/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/sketch/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/sketch/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/sketch/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/opt/homebrew/Caskroom/miniconda/base/envs/sketch/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/gregv/dev/Caffeine-Compilers--FromSketchestoSmiles-AColoringBookthatGivesBack/backend/suzie_api/api/views.py", line 64, in create
    creative_url = uploader.upload_file_to_s3(BytesIO(file_content), f'raw_sketch/{ts}.jpg')
  File "/Users/gregv/dev/Caffeine-Compilers--FromSketchestoSmiles-AColoringBookthatGivesBack/backend/suzie_api/api/s3_handler.py", line 16, in upload_file_to_s3
    self.s3.upload_fileobj(file_obj, self.bucket_name, file_name)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/sketch/lib/python3.10/site-packages/boto3/s3/inject.py", line 636, in upload_fileobj
    return future.result()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/sketch/lib/python3.10/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/sketch/lib/python3.10/site-packages/s3transfer/futures.py", line 266, in result
    raise self._exception
  File "/opt/homebrew/Caskroom/miniconda/base/envs/sketch/lib/python3.10/site-packages/s3transfer/tasks.py", line 139, in __call__
    return self._execute_main(kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/sketch/lib/python3.10/site-packages/s3transfer/tasks.py", line 162, in _execute_main
    return_value = self._main(**kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/sketch/lib/python3.10/site-packages/s3transfer/upload.py", line 764, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/sketch/lib/python3.10/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/sketch/lib/python3.10/site-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
[16/Feb/2024 02:46:26] "POST /api/upload_drawings/ HTTP/1.1" 500 145226
```

**Comment by gregv** [comment]
Had to add key
